name: Build and deploy

on:
  workflow_dispatch:
  pull_request:
  push:
    branches:
      - main
      - development
      - feat/proper-docker

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  contents: read
  packages: write

jobs:
  build:
    name: Build artifact with Contentful
    runs-on: ubuntu-latest
    environment: ${{ github.ref == 'refs/heads/main' && 'production' || 'development' }}

    defaults:
      run:
        shell: bash

    steps:
      - uses: actions/checkout@v4

      - name: Setup `bun` 🥟
        uses: oven-sh/setup-bun@v2

      - name: Install dependencies
        run: bun install

      - name: Generate a production build
        run: bun run build
        env:
          CONTENTFUL_SPACE_ID:       ${{ secrets.CONTENTFUL_SPACE_ID       }}
          CONTENTFUL_DELIVERY_TOKEN: ${{ secrets.CONTENTFUL_DELIVERY_TOKEN }}
          CONTENTFUL_ENVIRONMENT:    ${{ vars.CONTENTFUL_ENVIRONMENT }}      
      # Astro will produce a build in `dist/`
      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: website-build-static-files
          path: ./dist/
          retention-days: 45 # Default value is 90, and cannot be higher than that. Because of this we have the cron job above to prevent the latest artifact from being deleted without being replaced. Since we do that monthly anyway, we remove it earlier for we use less storage that way.


  docker:
    name: Package Docker image (httpd)
    needs: build
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Download build artifact
        uses: actions/download-artifact@v4
        with:
          name: website-build-static-files
          path: dist/

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Set image name
        run: echo "IMAGE=ghcr.io/${{ github.repository }}:${{ github.sha }}" >> $GITHUB_ENV

      - name: Login to GitHub Container Registry
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build Docker image
        run: docker build -t $IMAGE .

      - name: Push Docker image
        # if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/development'
        run: docker push $IMAGE